spring:
 profiles:
 #激活不同的profile test/dev/product
  active: dev
  incloud: dev,test,product,logtest,logtest2,logtest3

#自定义info信息
info:
 app:
  name: springboot-demo
  description: 学习学习的噢！
  version: 1.0.0
